#!/bin/bash
year=`date +'%Y'`
month=`date +'%m'`
day=`date +'%d'`

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -e|--edit)
    echo "TODO: -e"
    shift
    ;;
    -v|--verbose)
    echo "TODO: -v"
    shift
    ;;
    -c|--create)
    echo "TODO: -c"
    shift
    ;;
    -i|--info)
    echo "TODO: -i"
    shift
    ;;
    -h|--help)
    echo "TODO: -h"
    shift
    ;;
    -e|--edit)
    echo "TODO: -e"
    shift
    shift
    ;;
    *)
    echo "Unknown Argument."
    shift
    ;;
esac
done

if [ ! -f ~/notes/$year/$month/$day.md ]; then
    mkdir -p ~/notes/$year/$month/
    touch ~/notes/$year/$month/$day.md
    echo "$day-$month-$year\n---\n" > ~/notes/$year/$month/$day.md
    echo "Created new note: ~/notes/$year/$month/$day.md"
fi

vim ~/notes/$year/$month/$day.md
