#!/bin/bash

create_note () {
    if [ ! -f ~/notes/$year/$month/$day.md ]; then
        mkdir -p ~/notes/$year/$month/
        touch ~/notes/$year/$month/$day.md
        echo "$day-$month-$year\n---\n" > ~/notes/$year/$month/$day.md
        echo "Created new note: ~/notes/$year/$month/$day.md"
    else
        echo "Note \"~/notes/$year/$month/$day.md\" already exists."
    fi
    
}

year=`date +'%Y'`
month=`date +'%m'`
day=`date +'%d'`

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -e|--edit)
    echo "TODO: -e"
    shift
    shift
    ;;
    -p|--print)
    echo "TODO: -v"
    shift
    ;;
    -c|--create)
    create_note
    exit 0
    ;;
    -i|--info)
    echo "TODO: -i"
    shift
    ;;
    -h|--help)
    echo "note - Note Keeper 0.1 (01 Aug 2018)

Usage: note [arguments]

Arguments:
    -h | --help                         Display usage guide.
    -e | --edit <DATE: year-month-day>  Open a specific note for editing.
    -p | --print                        Print the contents of a note.
    -c | --create                       Create a note but don't open it for editing.
    -i | --info                         Print information about a note."
    exit 0
    ;;
    *)
    echo "Unknown Argument \"$1\""
    echo "Try \"note --help\" to see usage information."
    exit 0
    ;;
esac
done

if [ ! -f ~/notes/$year/$month/$day.md ]; then
    mkdir -p ~/notes/$year/$month/
    touch ~/notes/$year/$month/$day.md
    echo "$day-$month-$year\n---\n" > ~/notes/$year/$month/$day.md
    echo "Created new note: ~/notes/$year/$month/$day.md"
fi

vim ~/notes/$year/$month/$day.md
